markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-purgecss

author: "Oscar Franco"
url: "https://ospfranco.github.io"
title: "Señor Dev"
twitter:
  username: "ospfranco"
  card: ""
logo: "assets/taco.png"
future: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore
