markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss

author: "Oscar Franco"
url: "https://ospfranco.com"
title: "Oscar Franco"
twitter:
  username: "ospfranco"
  card: "summary"
image: "assets/profile.JPG"
future: true # Publish posts with future dates

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - README.md
  - postcss.config.js
  - bin
  - .gitignore

webrick:
  headers:
    Cache-Control: max-age=31536000

postcss:
  cache: false
